### ISSUE TITLE
Date return different values 

### ISSUE THREAD

**Issue by yueyin1992** [chelaxe/SwingingDoor#3]
Hi, 

I got an issue after I converted the date back to the original format using datetime.timestamp(). 
The dates are different from before. I tried your data, and it still got the same issue. Could you please help check?
For example, my data is a time series with 15 min resolution. But the result gives me one in 19 min. Thanks a lot.

Date | Value
2016-10-09 00:00:00 | 10
2016-10-09 00:19:32 | 9

Yue

**Comment by chelaxe** [comment]
`datetime.strptime("2016-10-09 00:00:00", "%Y-%m-%d %H:%M:%S").timestamp()`
1475953200.0

`datetime.strptime("2016-10-09 00:19:32", "%Y-%m-%d %H:%M:%S").timestamp()`
1475954372.0
